name: Setup Swift
description: Setup a Swift environment on Ubuntu or macOS 
author: Frederik Wallner
inputs:
  swift-version: 
    description: Swift version to configure
  swift-version-file:
    description: File containing the Swift version
    default: ".swift-version"
outputs:
  version:
    description: The full Swift version that was configured
runs:
  using: node16
  main: dist/index.js
branding:
  icon: 'command'  
  color: 'orange'
